# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='interface.proto',
  package='',
  serialized_pb='\n\x0finterface.proto\"\xac\x01\n\x03RPC\x12\x17\n\x04type\x18\x01 \x02(\x0e\x32\t.RPC.Type\"\x81\x01\n\x04Type\x12\x0f\n\x0bInitRequest\x10\x01\x12\x10\n\x0cInitResponse\x10\x02\x12\x0c\n\x08Topology\x10\x03\x12\x13\n\x0fPacketInRequest\x10\x04\x12\x14\n\x10PacketInResponse\x10\x05\x12\x0c\n\x08\x44\x61taPush\x10\x06\x12\x0f\n\x0b\x44\x61taReceive\x10\x07*\x08\x08\x65\x10\x80\x80\x80\x80\x02\";\n\x0bInitRequest\x12\x0b\n\x03ism\x18\x01 \x02(\t2\x1f\n\x03msg\x12\x04.RPC\x18\x65 \x02(\x0b\x32\x0c.InitRequest\"@\n\x0cInitResponse\x12\x0e\n\x06\x64omain\x18\x01 \x02(\x04\x32 \n\x03msg\x12\x04.RPC\x18\x66 \x02(\x0b\x32\r.InitResponse\"5\n\x08Topology\x12\x0b\n\x03\x64ot\x18\x01 \x02(\t2\x1c\n\x03msg\x12\x04.RPC\x18g \x02(\x0b\x32\t.Topology\"d\n\x0fPacketInRequest\x12\x0e\n\x06\x63ookie\x18\x01 \x02(\r\x12\x0c\n\x04srcV\x18\x02 \x02(\r\x12\x0e\n\x06packet\x18\x03 \x02(\x0c\x32#\n\x03msg\x12\x04.RPC\x18h \x02(\x0b\x32\x10.PacketInRequest\"\x91\x01\n\x10PacketInResponse\x12\x0e\n\x06\x63ookie\x18\x01 \x02(\r\x12\x0c\n\x04srcV\x18\x02 \x02(\r\x12\x0c\n\x04midV\x18\x03 \x01(\r\x12\x0c\n\x04\x64stV\x18\x04 \x02(\r\x12\r\n\x05match\x18\x05 \x02(\x0c\x12\x0e\n\x06\x61\x63tion\x18\x06 \x01(\x0c\x32$\n\x03msg\x12\x04.RPC\x18i \x02(\x0b\x32\x11.PacketInResponse\"R\n\x08\x44\x61taPush\x12\x0c\n\x04srcV\x18\x01 \x02(\x03\x12\x0c\n\x04\x64stV\x18\x02 \x02(\x03\x12\x0c\n\x04\x64\x61ta\x18\x03 \x02(\x0c\x32\x1c\n\x03msg\x12\x04.RPC\x18j \x02(\x0b\x32\t.DataPush\"J\n\x0b\x44\x61taReceive\x12\x0c\n\x04srcV\x18\x01 \x02(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x02(\x0c\x32\x1f\n\x03msg\x12\x04.RPC\x18k \x02(\x0b\x32\x0c.DataReceive')



_RPC_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='RPC.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='InitRequest', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='InitResponse', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='Topology', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PacketInRequest', index=3, number=4,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='PacketInResponse', index=4, number=5,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DataPush', index=5, number=6,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='DataReceive', index=6, number=7,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=53,
  serialized_end=182,
)


_RPC = descriptor.Descriptor(
  name='RPC',
  full_name='RPC',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='RPC.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RPC_TYPE,
  ],
  options=None,
  is_extendable=True,
  extension_ranges=[(101, 536870912), ],
  serialized_start=20,
  serialized_end=192,
)


_INITREQUEST = descriptor.Descriptor(
  name='InitRequest',
  full_name='InitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='ism', full_name='InitRequest.ism', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='InitRequest.msg', index=0,
      number=101, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=194,
  serialized_end=253,
)


_INITRESPONSE = descriptor.Descriptor(
  name='InitResponse',
  full_name='InitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='domain', full_name='InitResponse.domain', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='InitResponse.msg', index=0,
      number=102, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=255,
  serialized_end=319,
)


_TOPOLOGY = descriptor.Descriptor(
  name='Topology',
  full_name='Topology',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='dot', full_name='Topology.dot', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='Topology.msg', index=0,
      number=103, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=321,
  serialized_end=374,
)


_PACKETINREQUEST = descriptor.Descriptor(
  name='PacketInRequest',
  full_name='PacketInRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cookie', full_name='PacketInRequest.cookie', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='srcV', full_name='PacketInRequest.srcV', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='packet', full_name='PacketInRequest.packet', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='PacketInRequest.msg', index=0,
      number=104, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=376,
  serialized_end=476,
)


_PACKETINRESPONSE = descriptor.Descriptor(
  name='PacketInResponse',
  full_name='PacketInResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='cookie', full_name='PacketInResponse.cookie', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='srcV', full_name='PacketInResponse.srcV', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='midV', full_name='PacketInResponse.midV', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dstV', full_name='PacketInResponse.dstV', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='match', full_name='PacketInResponse.match', index=4,
      number=5, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='action', full_name='PacketInResponse.action', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='PacketInResponse.msg', index=0,
      number=105, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=479,
  serialized_end=624,
)


_DATAPUSH = descriptor.Descriptor(
  name='DataPush',
  full_name='DataPush',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='srcV', full_name='DataPush.srcV', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='dstV', full_name='DataPush.dstV', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='DataPush.data', index=2,
      number=3, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='DataPush.msg', index=0,
      number=106, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=626,
  serialized_end=708,
)


_DATARECEIVE = descriptor.Descriptor(
  name='DataReceive',
  full_name='DataReceive',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='srcV', full_name='DataReceive.srcV', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='data', full_name='DataReceive.data', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
    descriptor.FieldDescriptor(
      name='msg', full_name='DataReceive.msg', index=0,
      number=107, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=True, extension_scope=None,
      options=None),
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=710,
  serialized_end=784,
)

_RPC.fields_by_name['type'].enum_type = _RPC_TYPE
_RPC_TYPE.containing_type = _RPC;
DESCRIPTOR.message_types_by_name['RPC'] = _RPC
DESCRIPTOR.message_types_by_name['InitRequest'] = _INITREQUEST
DESCRIPTOR.message_types_by_name['InitResponse'] = _INITRESPONSE
DESCRIPTOR.message_types_by_name['Topology'] = _TOPOLOGY
DESCRIPTOR.message_types_by_name['PacketInRequest'] = _PACKETINREQUEST
DESCRIPTOR.message_types_by_name['PacketInResponse'] = _PACKETINRESPONSE
DESCRIPTOR.message_types_by_name['DataPush'] = _DATAPUSH
DESCRIPTOR.message_types_by_name['DataReceive'] = _DATARECEIVE

class RPC(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RPC
  
  # @@protoc_insertion_point(class_scope:RPC)

class InitRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITREQUEST
  
  # @@protoc_insertion_point(class_scope:InitRequest)

class InitResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITRESPONSE
  
  # @@protoc_insertion_point(class_scope:InitResponse)

class Topology(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TOPOLOGY
  
  # @@protoc_insertion_point(class_scope:Topology)

class PacketInRequest(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKETINREQUEST
  
  # @@protoc_insertion_point(class_scope:PacketInRequest)

class PacketInResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PACKETINRESPONSE
  
  # @@protoc_insertion_point(class_scope:PacketInResponse)

class DataPush(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATAPUSH
  
  # @@protoc_insertion_point(class_scope:DataPush)

class DataReceive(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _DATARECEIVE
  
  # @@protoc_insertion_point(class_scope:DataReceive)

_INITREQUEST.extensions_by_name['msg'].message_type = _INITREQUEST
RPC.RegisterExtension(_INITREQUEST.extensions_by_name['msg'])
_INITRESPONSE.extensions_by_name['msg'].message_type = _INITRESPONSE
RPC.RegisterExtension(_INITRESPONSE.extensions_by_name['msg'])
_TOPOLOGY.extensions_by_name['msg'].message_type = _TOPOLOGY
RPC.RegisterExtension(_TOPOLOGY.extensions_by_name['msg'])
_PACKETINREQUEST.extensions_by_name['msg'].message_type = _PACKETINREQUEST
RPC.RegisterExtension(_PACKETINREQUEST.extensions_by_name['msg'])
_PACKETINRESPONSE.extensions_by_name['msg'].message_type = _PACKETINRESPONSE
RPC.RegisterExtension(_PACKETINRESPONSE.extensions_by_name['msg'])
_DATAPUSH.extensions_by_name['msg'].message_type = _DATAPUSH
RPC.RegisterExtension(_DATAPUSH.extensions_by_name['msg'])
_DATARECEIVE.extensions_by_name['msg'].message_type = _DATARECEIVE
RPC.RegisterExtension(_DATARECEIVE.extensions_by_name['msg'])
# @@protoc_insertion_point(module_scope)
